// Web build: the same renderer as the Electron app, served as a static site.
// `npm run dev:web` / `npm run build:web` (output in dist/web, relative asset
// paths so it can live under any path). No main process: the renderer talks to
// Scryfall directly and keeps its data in IndexedDB (src/renderer/src/web/).
import { resolve } from 'path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const root = resolve(import.meta.dirname, 'src/renderer')

// The Electron page's CSP confines all network access to the main process; the
// web page must be allowed to reach Scryfall's API and image host instead.
const WEB_CSP = [
  "default-src 'self'",
  "img-src 'self' data: https://cards.scryfall.io https://api.scryfall.com",
  "style-src 'self' 'unsafe-inline'",
  "script-src 'self'",
  "connect-src 'self' https://api.scryfall.com stun: turn: turns:"
].join('; ')

function webCsp() {
  return {
    name: 'stack:web-csp',
    transformIndexHtml(html) {
      const re = /(<meta\s+http-equiv="Content-Security-Policy"\s+content=")[^"]*(")/
      if (!re.test(html)) throw new Error('index.html has no Content-Security-Policy meta tag to rewrite')
      return html.replace(re, `$1${WEB_CSP}$2`)
    }
  }
}

// The service worker: precaches the built app shell (every emitted file) and
// caches Scryfall card images as they are viewed, so the app opens and shows
// known cards without a network. Card data itself lives in IndexedDB.
function webServiceWorker() {
  return {
    name: 'stack:service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const files = ['./', './index.html', ...Object.keys(bundle).filter((f) => f !== 'sw.js').map((f) => './' + f)]
      const version = Date.now().toString(36)
      const source = `// Generated by vite.web.config.mjs — do not edit.
const SHELL = 'stack-shell-${version}'
const IMAGES = 'stack-images'
const PRECACHE = ${JSON.stringify(files)}
const IMAGE_HOSTS = ['cards.scryfall.io', 'api.scryfall.com']
const MAX_IMAGES = 3000

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('stack-shell-') && k !== SHELL).map((k) => caches.delete(k)))).then(() => self.clients.claim())
  )
})

// Keep the image cache bounded (oldest entries first).
async function trimImages() {
  const c = await caches.open(IMAGES)
  const keys = await c.keys()
  for (const k of keys.slice(0, Math.max(0, keys.length - MAX_IMAGES))) await c.delete(k)
}

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  // Card images: cache first, then network (opaque cross-origin responses are fine to store).
  if (IMAGE_HOSTS.includes(url.hostname) && req.destination === 'image') {
    e.respondWith(
      caches.open(IMAGES).then(async (c) => {
        const hit = await c.match(req)
        if (hit) return hit
        const res = await fetch(req)
        if (res && (res.ok || res.type === 'opaque')) {
          c.put(req, res.clone()).then(trimImages)
        }
        return res
      })
    )
    return
  }
  // The app shell: network first (so a new deploy shows up), cache when offline.
  if (url.origin === self.location.origin) {
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) caches.open(SHELL).then((c) => c.put(req, res.clone()))
          return res
        })
        .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit || (req.mode === 'navigate' ? caches.match('./index.html') : undefined)))
    )
  }
})
`
      this.emitFile({ type: 'asset', fileName: 'sw.js', source })
    }
  }
}

export default defineConfig({
  root,
  base: './',
  resolve: {
    alias: { '@engine': resolve(import.meta.dirname, 'src/shared/engine') }
  },
  server: {
    // Allow importing the shared engine, which lives outside the renderer root.
    fs: { allow: [resolve(import.meta.dirname)] }
  },
  build: {
    outDir: resolve(import.meta.dirname, 'dist/web'),
    emptyOutDir: true
  },
  plugins: [react(), webCsp(), webServiceWorker()]
})
